### PR TITLE
add version code

### PR DESCRIPTION
**Pull request by dulvui**
Hello Jokymon,

Since I saw that you used my godot-android-export action, I just wanted to see of it worked for you, and I found that the could be a problem with the VERSION_CODE variable, that is set from the version file. Sorry if the README does not cover this part.

So, given the version file `0.0.1-1`, the `VERSION_NAME=0.0.1` and  `VERSION_CODE=1` are created. Before the `-` is VERSION_NAME and after VERSION_CODE.

Here the part in the action that creates the version vars
```yml
  - name: Read version number and version code
    run: |
      echo "VERSION_NAME=$(cat version | cut -f1 -d-)" >> $GITHUB_ENV
      echo "VERSION_CODE=$(cat version | cut -f2 -d-)" >> $GITHUB_ENV
```

This pull request should fix the problem.

### CODE REVIEW

**Comment by Jokymon** [comment]
Thanks for the clarification! I was struggeling with the configurations for the export and didn't understand what was happening. I will merge your PR and check what's happening

**Comment by dulvui** [comment]
You are welcome! I reverted the latest changes I made to 4.0.1 again, so this could solve some problems. You can simply re-run the action with the version 4.0.1
I also tried to export your game locally on my machine, and there I got the error
image

Maybe enabling `ETC2/ASTC` texture import could solve the problem

**Comment by Jokymon** [comment]
@dulvui thanks for all this effort, really appreciate it!!
I just retriggered the last build and we'll see what happens. Tomorrow I will also check these import settings. I wasn't aware that I am using any special file types or settings, but thanks for this hint.

**Comment by Jokymon** [comment]
Wuhuuuu, thanks @dulvui again, it finally works!! The Change to ETC2/ASTC seems to have done the trick together obviously with changing GitHub-Action permissions for deploying to releases.
I still get a lot of suspicous warnings and errors, but I do eventually get an APK.

One of the errors I got was the `ERROR: /home/runner/.config/godot/editor_settings-4.tres:1 - Parse Error: Expected '['` in line 1552 of the first working build log. I tried to fix this somehow in my fork of the godot export action: https://github.com/Jokymon/godot-android-export but I'm not really happy with the approach. I still need to figure out, how I can properly copy a file from out of an action into the currently processed repo. My assumption is, that using the approach through a `SETTINGS` environment variable doesn't work correctly when the text contains `[` and empty lines.
Then again, maybe all of this really is irrelevant, since the action works ;-)

**Comment by dulvui** [comment]
Great that it worked! You are welcome, I'm also happy to see that my work is useful to someone else too.
I checked and you might be right and I'm missing the first files of the edtior_settings-4.tres file
```tres
[gd_resource type="EditorSettings" format=3]

[resource]
export/android/android_sdk_path = "/usr/local/lib/android/sdk"
export/android/shutdown_adb_on_exit = true
export/android/force_system_user = false
export/android/debug_keystore = "${{ github.action_path }}/debug.keystore"
export/android/debug_keystore_user = "androiddebugkey"
export/android/debug_keystore_pass = "android"
```
I added it now to version v4.0.2 or simply v4, if you want to try. I currently have no working Godot 4 game to try
https://github.com/dulvui/godot-android-export/blob/f02cd7436f0774affb54ae362093c0387d6f3421/action.yml#L67

**Pull request merged**
